Scumblr/config/routes.rb
#     Copyright 2014 Netflix, Inc.
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.


require 'sidekiq/web'

Scumblr::Application.routes.draw do

  resources :flags

  get "user_saved_filters/create"
  get "user_saved_filters/destroy"
  get "saved_filters/new"
  get "saved_filters/destroy"

  resources :saved_filters do
    member do
      post :add
      post :remove
    end
  end



  resources :results do
    collection do
      post 'update_multiple'
      post 'bulk_add'
      post 'search' => 'results#index'
      get 'search' => 'results#index'
      get 'tags/:tag', to: 'results#index', as: :tag
      get 'dashboard'
      get 'workflow_autocomplete'

    end

    member do
      post 'change_status/:status_id'=>"results#update_status", as: 'update_status'
      post 'comment'  => 'results#comment', :as=> :comment
      post 'tag'  => 'results#tag'
      post 'flag'  => 'results#flag'
      post 'action/:result_flag_id/step/:stage_id'  => 'results#action', as: 'action'
      post 'assign'  => 'results#assign'
      post 'subscribe'  => 'results#subscribe'
      post 'unsubscribe'  => 'results#unsubscribe'
      delete 'tags/:tag_id', to: 'results#delete_tag', as: :delete_tag
      post :add_attachment
      delete 'attachment/:attachment_id', to: 'results#delete_attachment', as: :delete_attachment
      post 'generate_screenshot' => "results#generate_screenshot"
      post 'update_screenshot'
      get 'update_screenshot'
    end


  end


  devise_for :users
  resources :users do
    member do
      post 'toggle_admin'
    end
  end




  resources :tags, only: :index

  resources :searches do
    collection do
      get 'options', to: 'providers#options'
      get 'run', to: 'searches#run'
      get :events
    end

    member do
      get 'run', to: 'searches#run'
    end

    member do
      get 'options', to: 'providers#options'
    end
  end


  resources :statuses do
    member do
      post 'set_default'
    end
  end





  get 'status', to: 'status#status'



  root to: "results#index"

  admin_constraint = lambda do |request|
    request.env['warden'].authenticate? && request.env['warden'].user.admin?
  end

  constraints admin_constraint do
    mount Workflowable::Engine => "/workflowable", as: :workflowable
    mount Sidekiq::Web => '/sidekiq'
    get 'errors', :to => "event_groups#index"
    get 'about', to: 'status#about'
  end

end

Scumblr/app/models/search.rb
#     Copyright 2014 Netflix, Inc.
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.


class Search < ActiveRecord::Base
  #  attr_accessible :description, :name, :options, :provider, :query, :tag_list

  has_many :taggings, as: :taggable, :dependent => :delete_all
  has_many :tags, through: :taggings
  has_many :subscribers, as: :subscribable
  has_many :search_results
  has_many :results, through: :search_results

  serialize :options, Hash


  validates :name, presence: true
  validates :name, uniqueness: true
  validate :validate_search



  accepts_nested_attributes_for :taggings, :tags


  def validate_search
    begin
      if(!SearchProvider::Provider.subclasses.include?(self.provider.try(:to_s).try(:constantize)))
        errors.add :search_provider, " must be specified"
        return
      end
    rescue
      errors.add :search_provider, " must be specified"
      return
    end


    provider_options = self.provider.constantize.options
    if(self.options.blank?)
      self.options = {}
    end
    self.options.slice!(*provider_options.keys)
    provider_options.each do |key, value|
      if value[:required] && options[key].blank?
        errors.add value[:name], " can't be blank"
      end
    end
  end


  def provider_name
    begin
      self.provider.to_s.constantize.provider_name
    rescue
      ""
    end
  end

  def provider_options
    begin
      self.provider.try(:constantize).try(:options) || {}
    rescue
      {}
    end
  end

  def tag_list
    tags.map(&:name).join(",")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      tag = Tag.where("lower(name) like lower(?)",n.strip).first_or_initialize
      tag.name = n if tag.new_record?
      tag.save if tag.changed?
      tag
    end
  end

  def subscriber_list
    subscribers.where(:user_id=>nil).map(&:email).join(",")
  end

  def subscriber_list=(emails)
    self.subscribers = emails.split(",").map do |email|
      self.subscribers.where(:email=>email.downcase.strip).first_or_initialize
    end
  end

  def perform_search
    search = self
    Rails.logger.warn "Searching #{search}"
    provider = search.provider.constantize
    results = provider.new(search.query, search.options).run
    Rails.logger.warn "Results #{results}"
    new_status = Status.find_by_default(true).try(:id)
    results.each do |r|

      result = Result.where(:url=>r[:url]).first_or_initialize
      result.title = r[:title]
      result.domain = r[:domain]
      result.metadata = r[:metadata] || {}
      result.status_id = new_status if !result.status_id && new_status

      result.save if result.changed?
      search.tags.each do |tag|
        tagging = result.taggings.where(:tag_id=>tag.id).first_or_initialize
        tagging.save if tagging.changed?
      end
      Rails.logger.warn "Result saved #{result}"

      search_result = SearchResult.where({:search_id=>search.id, :result_id=> result.id}).first_or_initialize
      search_result.save
      Rails.logger.warn "Search result saved #{search_result}"
    end

  end



end

Scumblr/app/controllers/searches_controller.rb
#     Copyright 2014 Netflix, Inc.
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.


class SearchesController < ApplicationController
  before_filter :load_search, only: [:show, :edit, :update, :destroy]
  authorize_resource



  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @searches }
    end
  end

  # GET /searches/1
  # GET /searches/1.json
  def show

    if (@search.provider.match(/\ASearchProvider::/) && SearchProvider::Provider.subclasses.include?(@search.provider.to_s.constantize) )
      @provider_options = @search.provider.constantize.options
    else
      @provider_options = []
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search }
    end
  end

  # GET /searches/new
  # GET /searches/new.json
  def new
    @search = Search.new
    @providers = search_providers

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @search }
    end
  end

  # GET /searches/1/edit
  def edit
    @providers = search_providers

  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)
    @providers = search_providers

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render json: @search, status: :created, location: @search }
      else
        format.html { render action: "new" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /searches/1
  # PUT /searches/1.json
  def update
    @providers = search_providers

    respond_to do |format|
      if @search.update_attributes(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy

    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :no_content }
    end
  end

  def run
    if(params[:id].present?)
      load_search

      #@search.perform_search
      SearchRunner.perform_async(@search.id)
      respond_to do |format|
        format.html {redirect_to search_url(@search), :notice=>"Running search..."}
      end
    else

      SearchRunner.perform_async(nil)

      respond_to do |format|
        format.html {redirect_to searches_url, :notice=>"Running all searches..."}
      end
    end

  end

  def events
    @statuses = []
    begin
      Sidekiq::Workers.new.each do |k,k2,v|
        @statuses << Sidekiq::Status.get_all(v["payload"]["jid"])
      end
      @statuses.sort!{|x,y| x["message"].to_s[0] <=> y["message"].to_s[0]}
    rescue Redis::CannotConnectError
    end
  end


  private

  def load_search
    @search = Search.find(params[:id])
  end

  #  attr_accessible :description, :name, :options, :provider, :query, :tag_list
  #accepts_nested_attributes_for :taggings, :tags
  def search_params
    all_options = params.require(:search).fetch(:options, nil).try(:permit!)
    params.require(:search).permit(:name, :description, :provider, :query, :tag_list, :subscriber_list).merge(:options =>all_options)
  end

  def search_providers
    SearchProvider::Provider.subclasses.map{|p| [p.to_s,p.provider_name]}.sort
  end


end

Scumblr/app/helpers/searches_helper.rb
#     Copyright 2014 Netflix, Inc.
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.


module SearchesHelper
end

Scumblr/app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %>
        prohibited this search from being saved:</h2>
      <ul>
        <% @search.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :query %><br />
    <%= f.text_field :query %>
  </div>
  <div class="field">
    <%= f.label :provider %><br />
    <%= f.collection_select :provider, @providers, :first, :last, {prompt: "Search provider"}, {id: :provider_field, "data-source"=> @search.new_record? ? options_searches_path : options_search_path(@search) } %>
  </div>
  <div id="provider_options">
    <%= render partial: 'providers/options_fields', locals: {search_options: @search.options, provider_options: @search.provider_options} %>
  </div>
  <div id="tags">
    <%= f.label :tags %><br />
    <%= f.hidden_field "tag_list", {value: @search.tag_list, class: "remote_select2", "data-multiple"=>true, "data-id-attribute"=>"name" , "data-parse-initial"=>"true", "data-create-new"=>"true", "data-object"=>"tags", "data-attribute"=>"name" , "data-path"=>tags_path} %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <%= f.submit class: "button" %>
  <%= link_to 'Back', searches_path, class: "button secondary" %>
<% end %>

Scumblr/app/views/searches/_statuses.html.erb
<ul>
  <li class="row">
    <label>
      Search Job Status
    </label>
  </li>
  <% if statuses.present? %>
    <% statuses.each do |status| %>
      <li>
        <a href="#">
          <% pct = (100*status["num"].to_f/status["total"].to_f).round(2) %>
          <div class="title"><%= status["message"].gsub(/\A.:/ , "").to_s %></div>
          <div class="subtitle"><%= pct%>%</div>
          <div class="progress">
            <span class="meter" style="width: <%= pct.to_i.to_s%>%"></span>
          </div>
        </a>
      </li>
    <% end %>
  <% else %>
    <li>
      <a class="italic" href="#">
        <div class="heading">
          No jobs running.
        </div>
      </a>
    </li>
  <% end %>
</ul>

Scumblr/app/views/searches/edit.html.erb
<h1>Editing search</h1>
<%= render 'form' %>

Scumblr/app/views/searches/events.js.erb
SearchStatusPoller.addStatuses("<%= j render partial:'statuses', locals:{statuses: @statuses} %>");
$('#task_count').html("<%= escape_javascript("<label class='label radius'>#{@statuses.count}</label>".html_safe) %>");

Scumblr/app/views/searches/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Provider</th>
    <th>Query</th>
    <th></th>
  </tr>
  <% @searches.each do |search| %>
    <tr>
      <td><%= link_to search.name, search %></td>
      <td><%= search.provider_name %></td>
      <td><%= search.query %></td>
      <td>
        <%= link_to 'Edit', edit_search_path(search), class: "button tiny" if can? :edit, search %>
        <%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' }, class: "button tiny alert" if can? :destroy, search %></td>
    </tr>
  <% end %>
</table>
<br />
<%= link_to 'New Search', new_search_path, class: "button" if can? :create, Search %>
<%= link_to 'Run All Searches', run_searches_path, class: "button alert" if can? :run, Search  %>

Scumblr/app/views/searches/new.html.erb
<h1>New search</h1>
<%= render 'form' %>

Scumblr/app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>
<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @search.name %></dd>
  <dt>Provider:</dt>
  <dd><%= @search.provider_name %></dd>
  <dt>Query:</dt>
  <dd><%= @search.query %></dd>
  <% @provider_options.each do |key, value| %>
    <dt><%= value[:name] %>:</dt>
    <dd><%= @search.options[key].to_s %></dd>
  <% end %>
  <dt>Description:</dt>
  <dd><%= @search.description %></dd>
  <dt>Tags:</dt>
  <dd>
    <% @search.tags.select{|t| t.value == nil}.each do |tag| %>
      <span class="label" <%= "style=background-color:#{tag.color||'#CCC'}"%> >
        <%= tag.name %>
      </span>
    <% end %>
  </dd>
  <dt>Subscribers:</dt>
  <dd><%= @search.subscriber_list %></dd>
</dl>
<%= link_to 'Edit', edit_search_path(@search), class: "button" if can? :edit, @search %>
<%= link_to 'Back', searches_path, class: "button secondary" if can? :index, Search %>
<%= link_to 'Run Now', run_search_path(@search), class: "button alert" if can? :run, @search %>