Scumblr/config/routes.rb
#     Copyright 2014 Netflix, Inc.
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.


require 'sidekiq/web'

Scumblr::Application.routes.draw do

  resources :flags

  get "user_saved_filters/create"
  get "user_saved_filters/destroy"
  get "saved_filters/new"
  get "saved_filters/destroy"

  resources :saved_filters do
    member do
      post :add
      post :remove
    end
  end



  resources :results do
    collection do
      post 'update_multiple'
      post 'bulk_add'
      post 'search' => 'results#index'
      get 'search' => 'results#index'
      get 'tags/:tag', to: 'results#index', as: :tag
      get 'dashboard'
      get 'workflow_autocomplete'

    end

    member do
      post 'change_status/:status_id'=>"results#update_status", as: 'update_status'
      post 'comment'  => 'results#comment', :as=> :comment
      post 'tag'  => 'results#tag'
      post 'flag'  => 'results#flag'
      post 'action/:result_flag_id/step/:stage_id'  => 'results#action', as: 'action'
      post 'assign'  => 'results#assign'
      post 'subscribe'  => 'results#subscribe'
      post 'unsubscribe'  => 'results#unsubscribe'
      delete 'tags/:tag_id', to: 'results#delete_tag', as: :delete_tag
      post :add_attachment
      delete 'attachment/:attachment_id', to: 'results#delete_attachment', as: :delete_attachment
      post 'generate_screenshot' => "results#generate_screenshot"
      post 'update_screenshot'
      get 'update_screenshot'
    end


  end


  devise_for :users
  resources :users do
    member do
      post 'toggle_admin'
    end
  end




  resources :tags, only: :index

  resources :searches do
    collection do
      get 'options', to: 'providers#options'
      get 'run', to: 'searches#run'
      get :events
    end

    member do
      get 'run', to: 'searches#run'
    end

    member do
      get 'options', to: 'providers#options'
    end
  end


  resources :statuses do
    member do
      post 'set_default'
    end
  end





  get 'status', to: 'status#status'



  root to: "results#index"

  admin_constraint = lambda do |request|
    request.env['warden'].authenticate? && request.env['warden'].user.admin?
  end

  constraints admin_constraint do
    mount Workflowable::Engine => "/workflowable", as: :workflowable
    mount Sidekiq::Web => '/sidekiq'
    get 'errors', :to => "event_groups#index"
    get 'about', to: 'status#about'
  end

end

Scumblr/app/models/saved_filter.rb
#     Copyright 2014 Netflix, Inc.
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.


class SavedFilter < ActiveRecord::Base
  belongs_to :user
  serialize :query
  has_many :user_saved_filters, :dependent=>:delete_all
  has_many :users, :through=> :user_saved_filters
  has_many :subscribers, as: :subscribable
  has_many :summaries, as: :summarizable

  validates :name, :presence => true

  def subscriber_list
    subscribers.where(:user_id=>nil).map(&:email).join(",")
  end

  def subscriber_list=(emails)
    self.subscribers = emails.split(",").map do |email|
      self.subscribers.where(:email=>email.downcase.strip).first_or_initialize
    end
  end

  def perform_search(query_overrides={})
    Result.perform_search(self.query.merge(query_overrides))

  end


end

Scumblr/app/controllers/saved_filters_controller.rb
#     Copyright 2014 Netflix, Inc.
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.


class SavedFiltersController < ApplicationController
  before_filter :set_header
  before_filter :load_saved_filter, only: [:show, :edit, :update, :destroy, :add, :remove]
  authorize_resource


  def index
    @saved_filters = current_user.saved_filters
    @added_public_saved_filters = current_user.added_saved_filters
    @public_saved_filters = SavedFilter.where(:public=>true).where.not(:user_id=>current_user.id).where.not(:id=>@added_public_saved_filters)


  end

  def create
    @saved_filter = SavedFilter.new(saved_filter_params)
    @saved_filter.user_id = current_user.id
    @saved_filter.query = params[:q]

    respond_to do |format|
      if @saved_filter.save
        format.html { redirect_to results_path, notice: 'Filter was successfully created.' }
        #format.json { render json: @saved_filter, status: :created, location: @saved_filter }
      else
        format.html { redirect_to results_path, notice: 'Could not save filter.' }
        #format.json { render json: @saved_filter.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    if(@saved_filter.user_id == current_user.id)
      @q = Result.includes(:tags,:status, :search_results).search(@saved_filter.query)
    else
      redirect_to saved_filters_path, notice: 'Could not edit filter.'
      return
    end
  end

  def update
    if(@saved_filter.user_id == current_user.id)

      @saved_filter.query = params[:q]
      respond_to do |format|
        if @saved_filter.update_attributes(saved_filter_params)
          format.html { redirect_to saved_filters_path, notice: 'Filter was successfully updated.' }
          #format.json { head :no_content }
        else
          format.html { render action: "edit" }

        end
      end
    else
      redirect_to saved_filters_path, notice: 'Could not update filter.'
      return
    end

  end

  def add
    if(@saved_filter.user_id != current_user.id && @saved_filter.public == true && !(current_user.user_saved_filters.include?(@saved_filter)))
      current_user.added_saved_filters << @saved_filter
      redirect_to saved_filters_path, notice: 'Filter added.'
    else
      redirect_to saved_filters_path, notice: 'Could not add filter.'
    end
  end

  def remove
    current_user.added_saved_filters.delete(@saved_filter)
    redirect_to saved_filters_path, notice: 'Filter removed.'

  end



  def destroy
    if(@saved_filter.user_id == current_user.id)
      @saved_filter.destroy

      respond_to do |format|
        format.html { redirect_to saved_filters_url }
        format.json { head :no_content }
      end

    else
      redirect_to saved_filters_path, notice: 'Could not destroy filter.'
    end


  end


  private

  def saved_filter_params
    params.require(:saved_filter).permit(:public, :name, :subscriber_list)
  end

  def load_saved_filter
    @saved_filter = SavedFilter.find(params[:id])
  end

  def set_header
    @header_title = "Saved Filters"
  end




end

Scumblr/app/helpers/saved_filters_helper.rb
#     Copyright 2014 Netflix, Inc.
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.


module SavedFiltersHelper
end

Scumblr/app/views/saved_filters/_form.html.erb
<%= form_for @saved_filter, id:"search_form"  do |f| %>
  <% if @saved_filter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@saved_filter.errors.count, "error") %>
        prohibited this result from being saved:</h2>
      <ul>
        <% @saved_filter.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h4>Filter Details</h4>
  <%= label_tag do %>Name
    <%= f.text_field :name %>
  <% end %>
  <div id="subscribers">
    <%= f.label :subscribers %><br />
    <%= f.hidden_field "subscriber_list", {value: @saved_filter.subscriber_list, class: "remote_select2", "data-multiple"=>true, "data-id-attribute"=>"email" , "data-parse-initial"=>"true", "data-create-new"=>"true", "data-object"=>"users", "data-attribute"=>"email" , "data-path"=>users_path} %>
  </div>
  <%= f.check_box :public %>
  <%= label_tag "Share publicly?" %><br/>
  <h4>Filter Criteria</h4>
  <%= fields_for @q do |f2| %>
    <%= render partial: 'results/search_fields', locals: {f: f2}%>
  <% end %>
  <%= f.submit class: "button small" %>
  <%#= f.button "Reset", type: :reset, class:"secondary" %>
<% end %>

Scumblr/app/views/saved_filters/destroy.html.erb
<h1>SavedFilters#destroy</h1>
<p>Find me in app/views/saved_filters/destroy.html.erb</p>

Scumblr/app/views/saved_filters/edit.html.erb
<%= render 'saved_filters/form' %>

Scumblr/app/views/saved_filters/index.html.erb
<h3>Saved Filters</h3>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Public</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @saved_filters.each do |filter| %>
      <tr>
        <td><%= filter.name %></td>
        <td><%= filter.public %></td>
        <td>
          <%= link_to "Show Results", search_results_path(:saved_filter_id=>filter.id), class: "button tiny" %>
          <%= link_to "Edit", edit_saved_filter_path(filter), class: "button tiny" %>
          <%= link_to 'Destroy', filter, method: :delete, data: { confirm: 'Are you sure?' }, class: "button tiny alert" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <h3>Public Filters<h3>
        <% @added_public_saved_filters.each do |filter| %>
          <tr>
            <td><%= filter.name %></td>
            <td>
              <%= link_to "Show Results", search_results_path(:saved_filter_id=>filter.id), class: "button tiny" %>
              <%= link_to "Remove", remove_saved_filter_path(filter.id),:method=>:post, class: "button tiny" %>
            </td>
          </tr>
        <% end %>
        <% @public_saved_filters.each do |filter| %>
          <tr>
            <td><%= filter.name %></td>
            <td>
              <%= link_to "Show Results", search_results_path(:saved_filter_id=>filter.id), class: "button tiny" %>
              <%= link_to "Add", add_saved_filter_path(filter.id), :method=>:post, class: "button tiny" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

Scumblr/app/views/saved_filters/new.html.erb
<%= render 'saved_filters/form' %>