Scumblr/config/routes.rb
#     Copyright 2014 Netflix, Inc.
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.


require 'sidekiq/web'

Scumblr::Application.routes.draw do

  resources :flags

  get "user_saved_filters/create"
  get "user_saved_filters/destroy"
  get "saved_filters/new"
  get "saved_filters/destroy"

  resources :saved_filters do
    member do
      post :add
      post :remove
    end
  end



  resources :results do
    collection do
      post 'update_multiple'
      post 'bulk_add'
      post 'search' => 'results#index'
      get 'search' => 'results#index'
      get 'tags/:tag', to: 'results#index', as: :tag
      get 'dashboard'
      get 'workflow_autocomplete'

    end

    member do
      post 'change_status/:status_id'=>"results#update_status", as: 'update_status'
      post 'comment'  => 'results#comment', :as=> :comment
      post 'tag'  => 'results#tag'
      post 'flag'  => 'results#flag'
      post 'action/:result_flag_id/step/:stage_id'  => 'results#action', as: 'action'
      post 'assign'  => 'results#assign'
      post 'subscribe'  => 'results#subscribe'
      post 'unsubscribe'  => 'results#unsubscribe'
      delete 'tags/:tag_id', to: 'results#delete_tag', as: :delete_tag
      post :add_attachment
      delete 'attachment/:attachment_id', to: 'results#delete_attachment', as: :delete_attachment
      post 'generate_screenshot' => "results#generate_screenshot"
      post 'update_screenshot'
      get 'update_screenshot'
    end


  end


  devise_for :users
  resources :users do
    member do
      post 'toggle_admin'
    end
  end




  resources :tags, only: :index

  resources :searches do
    collection do
      get 'options', to: 'providers#options'
      get 'run', to: 'searches#run'
      get :events
    end

    member do
      get 'run', to: 'searches#run'
    end

    member do
      get 'options', to: 'providers#options'
    end
  end


  resources :statuses do
    member do
      post 'set_default'
    end
  end





  get 'status', to: 'status#status'



  root to: "results#index"

  admin_constraint = lambda do |request|
    request.env['warden'].authenticate? && request.env['warden'].user.admin?
  end

  constraints admin_constraint do
    mount Workflowable::Engine => "/workflowable", as: :workflowable
    mount Sidekiq::Web => '/sidekiq'
    get 'errors', :to => "event_groups#index"
    get 'about', to: 'status#about'
  end

end

Scumblr/app/models/flag.rb
#     Copyright 2014 Netflix, Inc.
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.


class Flag < ActiveRecord::Base
  has_many :result_flags
  has_many :results, through: :result_flags
  has_many :subscribers, as: :subscribable
  belongs_to :workflow, class_name: "Workflowable::Workflow"

  has_many :subscribers, as: :subscribable

  validate :name, presence: true
  validate :name, uniqueness: true

  def subscriber_list
    subscribers.where(:user_id=>nil).map(&:email).join(",")
  end

  def subscriber_list=(emails)
    self.subscribers = emails.split(",").map do |email|
      self.subscribers.where(:email=>email.downcase.strip).first_or_initialize
    end
  end

end

Scumblr/app/controllers/results_controller.rb
#     Copyright 2014 Netflix, Inc.
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.


require 'open-uri'

class ResultsController < ApplicationController
  authorize_resource
  skip_before_filter :verify_authenticity_token, :only=>[:index, :update_screenshot]

  before_filter :load_result, only: [:show, :edit, :update, :destroy, :tag, :action,
                                     :flag, :update_status, :comment, :delete_tag, :assign, :add_attachment, :delete_attachment,
                                     :subscribe, :unsubscribe, :update_screenshot]

  skip_authorize_resource :only=>:update_screenshot
  skip_authorization_check :only=>:update_screenshot
  skip_before_filter :authenticate_user!, :only=>:update_screenshot

  # GET /results
  # GET /results.json
  def index

    

    perform_search

    #Save is here because if we render/return in perform_search we end up double rendering
    if(params[:commit] == "Save")
      #We delete commit to prevent the parameter value from being picked up in pagination, etc.
      params.delete(:commit)
      render 'saved_filters/new'
      return
    end

    @results = @results.page(params[:page]).per(params[:per_page]) if @results

    #We delete commit to prevent the parameter value from being picked up in pagination, etc.
    params.delete(:commit)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @results }
    end
  end


  def dashboard


    #Add boxes at the top with Quick facts (New today (delta))......
    # Providers/Search with highest/lowest signal to noise ratio
    # Providers/Search with most/least raw actionable results
    #

    @results = Result.all
    @flags = Flag.all
    @results_by_date = Result.where(:id=>@results).group("date(created_at)").order("date(created_at)").count
    @statuses= Status.all
    @searches = Search.all


    @flag_counts = ResultFlag.includes(:flag).where(:result_id=>@results).group("flags.name").count

    @search_results_total = Search.joins(:search_results).group("searches.id").count
    @search_results_24_hours = Search.joins(:search_results).group("searches.id").where("search_results.created_at > ?",1.day.ago).count
    @search_results_7_days = Search.joins(:search_results).group("searches.id").where("search_results.created_at > ?",7.days.ago).count
    @search_results_30_day_trend = Search.joins(:search_results).where("search_results.created_at > ?",30.days.ago).count(:group=>["searches.id", "date(search_results.created_at)"], :order=>"date(search_results.created_at)")


    @search_results_without_flags = Search.joins(:results).where.not(:id=>ResultFlag.select(:id)).references(:results).group("searches.id").count
    @search_results_with_flags = Search.joins(:results=>:flags).group(["searches.id", "flags.id"]).count


    render layout: "dashboard"

  end


  # GET /results/1
  # GET /results/1.json
  def show

    @comments = @result.root_comments.includes([:user,:children])

    @associated_objects = [
      {:method=>:search_results, :includes=>:search, :link=>{:method=>:search_id, :path=>:search_url, :params=>[:search_id]}, :attributes=>[:search_name, :provider, :query, :created_at], name:"Results"},
    ]

    @associated_objects.each do |result_set|
      get_paginated_results(@result, result_set[:method], result_set[:includes])
    end


    if(params[:action_name])
      @associated_objects = @associated_objects.select{|obj| obj[:method].to_s == params[:action_name].to_s}
    end



    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @result }
      format.js
    end
  end

  # GET /results/new
  # GET /results/new.json
  def new
    @result = Result.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @result }
    end
  end

  # GET /results/1/edit
  def edit

  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)
    @result.status = Status.find_by_default(true)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render json: @result, status: :created, location: @result }
      else
        format.html { render action: "new" }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /results/1
  # PUT /results/1.json
  def update

    respond_to do |format|
      if @result.update_attributes(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_status
    @status = Status.find(params[:status_id])

    @result.status_id= @status.id
    @result.save
    @notice = "Status updated."

    respond_to do |format|

      format.js
    end

  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy

    respond_to do |format|
      format.html { redirect_to results_url }
      format.json { head :no_content }
    end
  end

  def comment
    @comment = Comment.build_from( @result, current_user.id, params[:comment] )


    if(params[:parent_id] && parent = Comment.find_comments_for_commentable(Result, @result).find(params[:parent_id]))
      @comment.parent_id = params[:parent_id]
    end
    @comment.save


    redirect_to :back, notice: "Comment Added"
  end

  def delete_tag
    @result.taggings.where(:tag_id=>params[:tag_id]).delete_all
    redirect_to :back, notice: "Tag removed."

  end

  def assign
    @user = User.find(params[:user_id])

    @result.user_id = @user.id
    @result.save

    respond_to do |format|
      format.js
    end



  end

  def flag

    @notice=""
    @options=""

    if(@result.flags.map(&:id).include?(params[:flag].to_i))
      @notice = "Result already flagged!"
      return
    end

    @flag = Flag.find_by_id(params[:flag])
    @result_flag = @result.result_flags.where(:flag_id => @flag.id, :workflow_id=>@flag.workflow_id).first_or_initialize




    @errors = @result_flag.validate_actions(@flag.workflow.initial_stage_id, params[:options])

    if(@errors == nil)
      @result_flag.workflow_options = params[:options]
      @result_flag.current_user = current_user
      @result_flag.save
      @notice = "Result flagged!"

      #Not sure why this is necessary...
      @result.reload
      @result.result_flags.reload
    else
      @options = @result_flag.next_step_options(@flag.workflow.initial_stage_id, params[:options], current_user)
    end

  end


  def workflow_autocomplete
    @workflow = Workflowable::Workflow.find_by_id(params[:workflow_id])
    @stage = Workflowable::Stage.find_by_id(params[:stage_id])
    @action = @stage.before_actions.find_by_name(params[:action_id]) || @stage.after_actions.find_by_name(params[:action_id]) || @workflow.actions.find_by_name(params[:action_id])
    matches = @action.autocomplete(params[:field_type], params[:q])
    respond_to do |format|
      format.json { render json: matches, meta: {total: matches.count} }
    end
  end


  def action

    @notice=""
    @options=""
    @result = Result.find(params[:id])
    @result_flag = @result.result_flags.find_by_id(params[:result_flag_id])
    @next_stage = @result_flag.stage.next_steps.find_by_id(params[:stage_id])



    @errors = @result_flag.validate_actions(@next_stage.id, params[:options], current_user)
    if(@errors == nil)

      @result_flag.set_stage(@next_stage.id, params[:options], current_user )
      @result.reload
      @result.result_flags.reload
      @notice = "Stage changed!"

    else
      @options = @result_flag.next_step_options(@next_stage.id, params[:options], current_user)
    end
  end

  def tag

    params.try(:[],:tags).to_s.split(",").map do |tag_info|
      tag, color = tag_info.split("::")
      name, value = tag.split(":")


      t = Tag.where({name: name.to_s.strip, value:value.to_s.strip}).first_or_initialize
      t.color = color if color
      t.save! if t.changed?
      @result.taggings.find_or_create_by_tag_id(t.id)
    end

    redirect_to :back, notice: "Result tagged."

  end

  def add_attachment
    @result.result_attachments.create(params.require(:result_attachment).permit(:attachment))
    redirect_to :back, notice: "Attachment created."

  end

  def delete_attachment

    @result.result_attachments.where(:id=>params[:attachment_id]).delete_all
    redirect_to :back, notice: "Attachment removed."
  end

  def generate_screenshot

    if(params[:id].present?)
      load_result

      #@search.perform_search
      ScreenshotRunner.perform_async(@result.id)
      respond_to do |format|
        format.html {redirect_to result_url(@result), :notice=>"Attempting to generate a screenshot..."}
      end
    else

      ScreenshotRunner.perform_async(nil)

      respond_to do |format|
        format.html {redirect_to results_url, :notice=>"Attempting to generate screenshots..."}
      end
    end
  end

  def update_multiple
    result_ids = params[:result_ids]
    commit = params[:commit]
    if(params[:update_all_from_query] == "true")
      perform_search
      result_ids = @results.map{|r| r.id}
    end


    if(commit == "Update and Generate Screenshot")

Scumblr/app/helpers/results_helper.rb
#     Copyright 2014 Netflix, Inc.
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.


module ResultsHelper
end

Scumblr/app/views/results/_result_workflow.html.erb
<dl class="dl-horizontal">
    <% if @result.result_flags.count == 0 %>
      <h5>No workflows specified.</h5>
    <% end %>
    <% @result.result_flags.each do |result_flag| %>
      <dt class="half"><%= result_flag.try(:flag).try(:name) %></dt>
      <dd>
      <a href="#" data-dropdown="drop<%= result_flag.id %>" class="button dropdown tiny secondary"><%= result_flag.stage.try(:name) %></a><br>
      <ul id="drop<%= result_flag.id %>" data-dropdown-content class="f-dropdown">
        <% result_flag.try(:stage).try(:next_steps).each do |next_step| %>
          <li><%= link_to next_step.name, action_result_path(@result, result_flag.id, next_step.id), remote: true, method: :post %></a></li>
        <% end %>
      </ul>
      </dd>
    <% end %>
</dl>

Scumblr/app/views/results/_results_tiles.html.erb
<ul class="small-block-grid-4">
  <% @results.each do |result| %>
    <li class="thumbnail-list-box">
      <div class="reveal-hidden">
        
        
          <% if result.result_attachments.length > 0 %>
            <%= image_tag result.result_attachments.last.attachment.expiring_url(6000, :medium), class: "thumbnail-image  thumbnail-list-image" %>
            <div class="thumbnail-buttons thumbnail-buttons-bg">

              <%= link_to "View Result", result_path(result), :class=>"hidden button tiny thumbnail-button" %>
              <span href="#" class="open_lightbox button tiny hidden thumbnail-button">View Images</span>
              <ul class="clearing-thumbs clearing-feature hide" data-clearing>
                <% result.result_attachments.reverse.each_with_index do |attr,i| %>
                  <li <%= " class=clearing-featured-img" if i==0 %>>
                    <%= link_to attr.attachment.expiring_url(6000) do %>
                      <%= image_tag attr.attachment.expiring_url(6000, :thumb) %>
                    <% end %>
                  </li>
                <% end %>
              </ul>
              <div class="centered hidden"><%= truncate(result.url) %></div>
            </div>
            
          <% else %>
            <%= link_to result_path(result) do %>
              <%= image_tag "scumblr_blank.png", class: "thumbnail-image" %>
              <div class="thumbnail-buttons thumbnail-buttons-bg">

                <%= link_to "View Result", result_path(result), :class=>"hidden button tiny thumbnail-button" %>
                <div class="centered hidden"><%= truncate(result.url) %></div>
            </div>
          <% end %>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

Scumblr/app/views/results/_show_details.html.erb
<h3>Details</h3>
<table>
  <tbody>
    <tr>
      <td class="header">Title</td>
      <td>
        <%= @result.title %>
        <% if @result.content.present? %>
          (<a href="#" data-reveal-id="contents-modal">View Contents</a>)
          <div id="contents-modal" class="reveal-modal" data-reveal>
            <h3>Result Contents</h3>
            <p><%= @result.content %></p>
          </div>
        <% end %>
      </td>
    </tr>
    <tr>
      <td class="header">URL</td>
      <td><%= link_to @result.url, @result.url, data: {confirm: "Are you sure? This will take you to a potentially dangerous site!\n\nURL: " + @result.url.to_s}, target:"_blank"  %></td>
    </tr>
    <tr>
      <td class="header">Identified</td>
      <td><%= time_ago_in_words(@result.created_at) + " ago" %></td>
    </tr>
    <% @result.metadata.keys.each do |key| %>
      <%= render partial: "results/metadata/#{key}_row" rescue nil %>
    <% end %>

  </tbody>
</table>

<% @result.metadata.keys.each do |key| %>
  <%= render partial: "results/metadata/#{key}_details" rescue nil %>
<% end %>

Scumblr/app/views/results/_update_workflow.html.erb
<div class="preloader"></div>
<header class="popup-header">
  <div class="row">
    <div class="large-12 columns">
      <h4>Update Workflow</h4>
    </div>
  </div>
</header>
<div class="row">
  <div class="large-12 columns">
    <% if @errors && params[:options].present? %>
      <% @errors.each do |error| %>
        <div data-alert="" class="alert-box">
          <p>Errors For:
            <%= error.keys.first.to_s.titleize %></p>
          <ul>
            <% error[error.keys.first].each do |e| %>
              <li><%= e.to_s.titleize %></li>
            <% end %>
          </ul><a href="#" class="close">×</a>
        </div>
      <% end %>
    <% end %>
    <%= form_for @result, :url=>action_result_path(@result, @result_flag, @next_stage), method: :post, remote: true do |f| %>
      <%= render partial: "workflow_options" %>
      <%= f.submit :class=>"button tiny preload" %>
      <%= button_tag "Cancel", :type=>:button, :class=>"button secondary tiny close-modal" %>
    <% end %>
  </div>
</div>

Scumblr/app/views/results/_workflow_options.html.erb
<% @options.each do |action_type, options| %>
  <% options.each do |k,v| %>
    <% if v.length > 0 %>
      <h5><%= k.titleize %></h5>
    <% end %>
    <%= fields_for "options[#{action_type}][#{k}]", OpenStruct.new({}) do |options_form| %>
      <% v.each do |key, value| %>
        <div class="field">
          <% if value[:value].blank? || value[:user_specified] ==true %>            
            <%= render partial: value[:type] ? "shared/workflowable/fields/#{value[:type]}" : "shared/workflowable/fields/string", locals: {f: options_form, label:value.try(:[],:name) || key, value_hash:value, value: params.try(:[], action_type).try(:[],k).try(:[],key) || value[:value] ||  value[:default], key:key, workflow_id: @flag.workflow_id, action_id:k} %>
          <% else %>
            <!-- <b><%= key.to_s.titleize %>: </b>
              <%#= value.try(:[],:value).try(:[],:name) if value.try(:[],:value).class == ActionController::Parameters %>
              <%#= value.try(:[],:value) if value.try(:[],:value).class != ActionController::Parameters %> -->
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>

Scumblr/app/views/results/action.js.erb
<% if @notice.present? %>
  $('#flash_messages').html("<%= escape_javascript(render :partial=>"shared/notification", :locals => {:message=>@notice}) %>");
<% end %>
<% if @options.present? %>
  $('#workflow_options_modal').html("<%= escape_javascript(render :partial=>"update_workflow", :locals => {}) %>");  
  $("#workflow_options_modal").foundation('reveal', 'open');
  
<% else %>
  $('#result_workflow').html("<%= escape_javascript(render :partial=>"result_workflow") %>");
  $('#result_details').html("<%= escape_javascript(render :partial=>"show_details") %>");
  $("#workflow_options_modal").foundation('reveal', 'close');
<% end %>

$(".workflow_form").hide();
ready();
hide_preloader();
$("#preloader-modal").foundation('reveal','close');

Scumblr/app/views/results/assign.js.erb
$('#assignee_value').html("<%= escape_javascript(render :partial=>"assignee", :locals => {:result=>@result}) %>").show();  
$('#flash_messages').html("<%= escape_javascript(render :partial=>"shared/notification", :locals => {:message=>"Assignee updated!"}) %>");
$('#assignee_select').hide();
$(function(){ $(document).foundation(); });

Scumblr/app/views/results/index.html.erb
<nav class="tab-bar">
  <section class="tab-bar-section">
    <h1>Results
      <span class="small-heading">
        <%= page_entries_info @results %>
        <% if @results.total_count != @total_result_count %><b>(<%= @total_result_count - @results.total_count %>
            results  filtered)</b><% end %>
      </span>
    </h1>
  </section>
  <section class="pagination">
    <%= paginate @results, :method=>:post, :params=> nil, :outer_window => 3, :window=>1, :remote=> (defined? remote)? remote : false %>
  </section>
  <section class="buttons button-bar">
    <ul class="button-group">
      <li><%= link_to "", results_path(:view=>"list"), :class=>"view-button fi-list-bullet" %></li>
      <li><%= link_to "", results_path(:view=>"tiles"), :class=>"view-button fi-thumbnails" %></li>
    </ul>
  </section>
</nav>
<div class="panel" style="display:none" id="update_all_from_page_header">
  <p>All
    <%= @results.count %>
    results on this page selected.
    <%= link_to "Select all #{@results.total_count} results that match this filter", "#", :id=>"update_all_from_query_link" %></p>
</div>
<div class="panel" style="display:none" id="update_all_from_query_header">
  <p>All
    <%= @results.total_count %>
    results in this search selected.
    <%= link_to "Clear selection", "#", :id=>"clear_selection" %></p>
</div>

<% if @view == "tiles" %>
  <%= render 'results_tiles' %>
<% else %>
  <%= render 'results_table' %>
<% end %>


<%= content_for :sidebar do %>
  <div class="sidebar" id="result_action_panel" style="display:none">
    <nav class="tab-bar">
      <section class="tab-bar-section">
        <h1>Actions
        </h1>
      </section>
    </nav>
    <section class="panel sidepanel">
      <%= form_tag update_multiple_results_path, method: :post, :id=>"update_results_form" do %>
        <%= label_tag do %>Status
          <%= select_tag :status_id, options_from_collection_for_select(Status.all, "id", "name"), {:prompt => 'Please select', class: 'select2'} %>
        <% end %>
        <%= label_tag do %>Tags
          <%= hidden_field_tag "tags", "", {class: "remote_select2", "data-multiple"=>true, "data-id-attribute"=>"name_value" , "data-parse-initial"=>"true", "data-create-new"=>"true", "data-object"=>"tags", "data-attribute"=>"name_value" , "data-path"=>tags_path} %>
        
        <% end %>  
        <%= label_tag "Remove" do %>
        <%= check_box_tag :remove_tags, '1', false %> Remove
        <% end %>

  
        <%= label_tag do %>Assignee
          <%= select_tag :assignee_id, options_from_collection_for_select(User.all, :id, :email), {:prompt => 'Please select', class: "select2"} %>
        <% end %>
        <%= hidden_field_tag :q, params[:q].to_json %>
        <%= hidden_field_tag :update_all_from_query, false, {:id=>'update_all_from_query'} %>
        <% button_options = ["Update", "Update and Generate Screenshot", "Update and Force Generate Screenshot"] %>
                
        
        <%= split_button  button_options, :button_class=>'small', :link_class=>'update_multiple_button' %>
        <% if(can? :destroy, Result) %>
          <%= submit_tag "Delete Results", class: "button alert small update_multiple_button", data: { confirm: "Are you sure you want to delete the selected results?" } %>
        <% end %>
      <% end %>
    </section>
  </div>
<% end %>
<%= paginate @results, :method=>:post, :params=> nil, :outer_window => 3, :window=>1, :remote=> (defined? remote)? remote : false %>
<br />
<%= link_to 'New Result', new_result_path, class: "button" %>
<%= link_to "Bulk Add Results", "#", :class=>"button", data:{"reveal-id"=>"bulk_add_form"} %>
<div id="bulk_add_form" class="reveal-modal custom-modal" data-reveal>
  <header class="popup-header">
    <div class="row">
      <div class="large-12 columns">
        <h4>Bulk Add Results</h4>
      </div>
    </div>
  </header>
  <div class="row">
    <div class="large-12 columns">
      <%= form_tag bulk_add_results_path do |f| %>
        <%= text_area_tag :results %> 
        <%= label_tag do %>Tags
          <%= hidden_field_tag "tags", "", {class: "remote_select2", "data-multiple"=>true, "data-id-attribute"=>"name_value" , "data-parse-initial"=>"true", "data-create-new"=>"true", "data-object"=>"tags", "data-attribute"=>"name_value" , "data-path"=>tags_path} %>
        
        <% end %>  
        <%= submit_tag "Submit", :class=>"button tiny preload" %>
        <%= button_tag "Cancel", :type=>:button, :class=>"button secondary tiny close-modal" %>
      <% end %>
    </div>
  </div>
</div>



<%= content_for :sidebar do %>
  <div class="sidebar">
    <nav class="tab-bar">
      <section class="tab-bar-section">
        <h1>Filter
        </h1>
      </section>
    </nav>
    <section class="panel sidepanel">
      <%= search_form_for @q, :url=>search_results_path, :method=>:post, :authenticity_token => false, id:"search_form"  do |f| %>
        <%= render partial: 'search_fields', locals: {f: f}%>
        <%= f.submit class: "button small" %>
        <%= f.submit "Clear Search", class: "button secondary small" %>
        <%= f.submit "Save", class: "button secondary small" %>
        <%#= f.button "Reset", type: :reset, class:"secondary" %>
      <% end %>
    </section>
  </div>
<% end %>

Scumblr/app/views/results/new.html.erb
<h1>New result</h1>
<%= render 'form' %>

Scumblr/app/views/results/show.js.erb
$('#div_<%= params[:uuid] %>').html("<%= escape_javascript(render :partial=>"shared/abstract_table", :locals => {:result_set=>@associated_objects[0]}) %>");  
$(function(){ $(document).foundation(); });

Scumblr/app/views/results/unsubscribe.js.erb
<% if @notice.present? %>
  $('#flash_messages').html("<%= escape_javascript(render :partial=>"shared/notification", :locals => {:message=>@notice}) %>");
<% end %>
$("#subscibers").html("<%= escape_javascript(render :partial=>"subscription") %>");
$("#subscribers-modal.open").html("<%= escape_javascript(render :partial=>"subscriber_list") %>");


ready();

Scumblr/app/views/results/update_multiple.html.erb
<%= params.inspect %>
<br/>
<%= @result_ids.count %>

Scumblr/app/views/results/update_status.js.erb
<% if @notice.present? %>
  $('#flash_messages').html("<%= escape_javascript(render :partial=>"shared/notification", :locals => {:message=>@notice}) %>");
<% end %>
$('div#status-bar').html("<%= escape_javascript(render :partial=>"status_bar", :locals => {:result=>@result}) %>");  


ready();